### PR TITLE
Extracted IRateLimitService to allow injecting a custom RateLimitService for Tests

### PR DESCRIPTION
**Pull request by sabine19**
Hi,

We would like to have the opportunity to override the RateLimitService to have a custom implementation for our Test Cases (as the rate limit is not needed there). 

- extracted an interface from the RateLimitService 
- updated Service Collection Extension to inject RateLimitService for IRateLimitService
- changed the calls to RateLimitService to using the injected IRateLimitService. 

Thanks!

Best Regards
Sabine

### CODE REVIEW

**Comment by sabine19** [comment]
Just a note on the implementation: 
As you probably know, there are more modern ways to implement this. (see https://www.devtrends.co.uk/blog/dependency-injection-in-action-filters-in-asp.net-core for example)
For Backwards Compatibility Reason I implemented it in this way. 
I can also do a refactoring to the IFilterFactory, but this will be a breaking change. 
What is your opinion @NicolasDorier?

**Comment by NicolasDorier** [comment]
Create one singleton and register it as both concrete type and interface. (existing code depends on the concrete type injection)
 We don't want to break existing code.

**Comment by sabine19** [comment]
Hi @NicolasDorier,
updated service registration to ensure backwards compatibility. Thanks.

**Comment by NicolasDorier** [comment]
Sorry for the lag, I pushed new version.

**Pull request merged**
